Repository art-here/art-here-backend, pull requests merged in 2023-06, with the labels that each got.

#104 [refactor] 게시물 세부 조회 리팩토링, 좋아요 싫어요 count 쿼리 수정
  src/docs/asciidoc/arts.adoc
  src/main/java/com/backend/arthere/post/application/PostService.java
  src/main/java/com/backend/arthere/post/domain/PostRepository.java
  src/main/java/com/backend/arthere/post/dto/response/PostResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/fixture/PostFixtures.java
  src/test/java/com/backend/arthere/post/presentation/PostControllerTest.java
Labels: docs, refactoring, test

#106 [feat] post 데이터 반환 API
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/post/application/PostService.java
  src/main/java/com/backend/arthere/post/domain/PostCustomRepository.java
  src/main/java/com/backend/arthere/post/domain/PostCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/post/domain/PostRepository.java
  src/main/java/com/backend/arthere/post/dto/response/PostInfoResponse.java
  src/main/java/com/backend/arthere/post/dto/response/PostsResponse.java
  src/main/java/com/backend/arthere/post/presentation/PostController.java
Labels: feat

#107 [feat] post 저장 api
  src/main/java/com/backend/arthere/post/application/PostService.java
  src/main/java/com/backend/arthere/post/dto/resquest/CreatePostsRequest.java
  src/main/java/com/backend/arthere/post/presentation/PostController.java
Labels: feat

#108 [Feat] post 수정 API 구현
  src/main/java/com/backend/arthere/post/application/PostService.java
  src/main/java/com/backend/arthere/post/domain/Post.java
  src/main/java/com/backend/arthere/post/dto/request/AddPostsRequest.java
  src/main/java/com/backend/arthere/post/dto/request/CreatePostsRequest.java
  src/main/java/com/backend/arthere/post/presentation/PostController.java
Labels: feat

#109 [feat] post 삭제 API 구현
  src/main/java/com/backend/arthere/post/application/PostService.java
  src/main/java/com/backend/arthere/post/presentation/PostController.java
Labels: feat

#110 [Feat] 이미지 URL 반환 데이터 추가
  src/main/java/com/backend/arthere/details/application/DetailsService.java
  src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
Labels: feat

#111 [refactor] 작품 이름 반환 추가
  src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
Labels: refactoring
