Repository art-here/art-here-backend, pull requests merged in 2023-02, with the labels that each got.

#21 [test] auth 테스트 코드를 구현한다.
  build.gradle
  src/main/java/com/backend/arthere/auth/application/AuthService.java
  src/main/java/com/backend/arthere/auth/dto/request/TokenRequest.java
  src/main/java/com/backend/arthere/auth/presentation/AuthController.java
  src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
  src/main/java/com/backend/arthere/global/error/ErrorResponse.java
  src/test/java/com/backend/arthere/auth/application/AuthServiceTest.java
  src/test/java/com/backend/arthere/auth/presentation/AuthControllerTest.java
  src/test/java/com/backend/arthere/auth/util/CookieUtilsTest.java
  src/test/java/com/backend/arthere/fixture/MemberFixtures.java
  src/test/java/com/backend/arthere/fixture/TokenFixtures.java
Labels: test, feat

#23 [test] jwt 테스트를 구현한다.
  src/main/java/com/backend/arthere/ArtHereApplication.java
  src/main/java/com/backend/arthere/auth/jwt/JwtTokenProvider.java
  src/main/java/com/backend/arthere/auth/presentation/AuthController.java
  src/main/java/com/backend/arthere/global/config/JpaConfig.java
  src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
  src/test/java/com/backend/arthere/auth/application/CustomUserDetailsServiceTest.java
  src/test/java/com/backend/arthere/auth/domain/TokenRepositoryTest.java
  src/test/java/com/backend/arthere/auth/domain/TokenTest.java
  src/test/java/com/backend/arthere/auth/jwt/JwtTokenAuthenticationFilterTest.java
  src/test/java/com/backend/arthere/auth/jwt/JwtTokenProviderTest.java
  src/test/java/com/backend/arthere/auth/presentation/AuthControllerTest.java
Labels: refactoring, test, fix

#25 [feat] 프론트엔드 포트 번호 변경
  src/main/java/com/backend/arthere/global/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: chore, help wanted, feat

#26 [docs] 스프링 rest docs를 구현한다.
  build.gradle
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/backend/arthere/auth/presentation/AuthController.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/global/error/ErrorResponse.java
  src/main/resources/static/docs/auth.html
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/auth/presentation/AuthControllerTest.java
  src/test/java/com/backend/arthere/global/ControllerTest.java
  src/test/java/com/backend/arthere/global/RestDocsConfig.java
Labels: docs, test, feat

#27 [feat] 로그인 로직 변경
  src/main/java/com/backend/arthere/auth/dto/response/LoginResponse.java
  src/main/java/com/backend/arthere/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/resources/application.yml
Labels: refactoring, fix, feat

#28 [feat] s3 이미지 공유, 업로드, 삭제 구현
  build.gradle
  src/docs/asciidoc/image.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/image/application/ImageService.java
  src/main/java/com/backend/arthere/image/dto/ImageResponse.java
  src/main/java/com/backend/arthere/image/dto/ImageUploadResponse.java
  src/main/java/com/backend/arthere/image/presentation/ImageController.java
  src/main/java/com/backend/arthere/image/util/PresignedURLUtils.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/backend/arthere/image/application/ImageServiceTest.java
  src/test/java/com/backend/arthere/image/presentation/ImageControllerTest.java
Labels: chore, feat

#34 [chore] QueryDSL 적용한다.
  build.gradle
  src/main/java/com/backend/arthere/global/config/QueryDslConfig.java
Labels: chore, feat

#37 [feat] 메인 화면 이미지 요청 API 구현
  src/main/java/com/backend/arthere/art/application/.gitkeep
  src/main/java/com/backend/arthere/art/domain/.gitkeep
  src/main/java/com/backend/arthere/art/dto/.gitkeep
  src/main/java/com/backend/arthere/art/exception/.gitkeep
  src/main/java/com/backend/arthere/art/presentation/.gitkeep
  src/main/java/com/backend/arthere/arts/application/ArtsService.java
  src/main/java/com/backend/arthere/arts/domain/Address.java
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepository.java
  src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/arts/domain/ArtsRepository.java
  src/main/java/com/backend/arthere/arts/domain/Category.java
  src/main/java/com/backend/arthere/arts/domain/Location.java
  src/main/java/com/backend/arthere/arts/dto/ArtImageResponse.java
  src/main/java/com/backend/arthere/arts/presentation/ArtsController.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/global/domain/BaseEntity.java
  src/test/java/com/backend/arthere/arts/domain/ArtsRepositoryTest.java
  src/test/java/com/backend/arthere/arts/presentation/ArtsControllerTest.java
  src/test/java/com/backend/arthere/auth/domain/TokenRepositoryTest.java
  src/test/java/com/backend/arthere/global/BaseControllerTest.java
  src/test/java/com/backend/arthere/image/presentation/ImageControllerTest.java
  src/test/java/com/backend/arthere/member/domain/MemberRepositoryTest.java
Labels: chore, feat

#39 [feat] map image API
  src/main/java/com/backend/arthere/arts/application/ArtsService.java
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepository.java
  src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/arts/dto/ArtImageByLocationResponse.java
  src/main/java/com/backend/arthere/arts/dto/LocationRangeResponse.java
  src/main/java/com/backend/arthere/arts/presentation/ArtsController.java
  src/main/java/com/backend/arthere/arts/util/LocationUtils.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/test/java/com/backend/arthere/arts/util/LocationUtilsTest.java
Labels: feat

#40 [feat] 작품 조회/저장 API 구현
  src/main/java/com/backend/arthere/arts/domain/Address.java
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/arts/domain/Category.java
  src/main/java/com/backend/arthere/arts/domain/Location.java
  src/main/java/com/backend/arthere/arts/exception/InvalidCategoryException.java
  src/main/java/com/backend/arthere/details/application/DetailsService.java
  src/main/java/com/backend/arthere/details/domain/Details.java
  src/main/java/com/backend/arthere/details/domain/DetailsRepository.java
  src/main/java/com/backend/arthere/details/domain/ExhibitionPeriod.java
  src/main/java/com/backend/arthere/details/dto/request/ArtRequest.java
  src/main/java/com/backend/arthere/details/dto/response/ArtMapResponse.java
  src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
  src/main/java/com/backend/arthere/details/dto/response/ArtSaveResponse.java
  src/main/java/com/backend/arthere/details/exception/DetailsNotFoundException.java
  src/main/java/com/backend/arthere/details/presentation/DetailsController.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
Labels: feat

#42 [test]/map image API 테스트 코드 추가, API 문서 작성
  src/docs/asciidoc/arts.adoc
  src/main/resources/static/docs/arts.html
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/arts/application/ArtsServiceTest.java
  src/test/java/com/backend/arthere/arts/domain/ArtsRepositoryTest.java
  src/test/java/com/backend/arthere/arts/presentation/ArtsControllerTest.java
Labels: docs, test

#47 [feat] 작품 수정/삭제 API 구현, 테스트 코드 작성
  src/docs/asciidoc/details.adoc
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/details/application/DetailsService.java
  src/main/java/com/backend/arthere/details/domain/Details.java
  src/main/java/com/backend/arthere/details/domain/DetailsRepository.java
  src/main/java/com/backend/arthere/details/presentation/DetailsController.java
  src/main/resources/static/docs/details.html
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/details/application/DetailsServiceTest.java
  src/test/java/com/backend/arthere/details/domain/DetailsRepositoryTest.java
  src/test/java/com/backend/arthere/details/domain/DetailsTest.java
  src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
  src/test/java/com/backend/arthere/fixture/EntireArtsFixtures.java
Labels: docs, test, feat

#50 [feat] 수정일 오름차순으로 no offset 적용
  src/docs/asciidoc/arts.adoc
  src/main/java/com/backend/arthere/arts/application/ArtsService.java
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepository.java
  src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/arts/dto/ArtImageByRevisionDateRequest.java
  src/main/java/com/backend/arthere/arts/dto/ArtImageByRevisionDateResponse.java
  src/main/java/com/backend/arthere/arts/presentation/ArtsController.java
  src/main/java/com/backend/arthere/global/validation/Date.java
  src/main/java/com/backend/arthere/global/validation/DateValidator.java
  src/main/resources/static/docs/arts.html
  src/main/resources/static/docs/details.html
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/arts/application/ArtsServiceTest.java
  src/test/java/com/backend/arthere/arts/domain/ArtsRepositoryTest.java
  src/test/java/com/backend/arthere/arts/presentation/ArtsControllerTest.java
Labels: docs, test, feat
