Repository art-here/art-here-backend, pull requests merged in 2023-01, with the labels that each got.

#4 [feat] 개발 디렉토리를 구축한다.
  build.gradle
  src/main/java/com/backend/arthere/art/application/.gitkeep
  src/main/java/com/backend/arthere/art/domain/.gitkeep
  src/main/java/com/backend/arthere/art/dto/.gitkeep
  src/main/java/com/backend/arthere/art/exception/.gitkeep
  src/main/java/com/backend/arthere/art/presentation/.gitkeep
  src/main/java/com/backend/arthere/category/application/.gitkeep
  src/main/java/com/backend/arthere/category/domain/.gitkeep
  src/main/java/com/backend/arthere/category/dto/.gitkeep
  src/main/java/com/backend/arthere/category/exception/.gitkeep
  src/main/java/com/backend/arthere/category/presentation/.gitkeep
  src/main/java/com/backend/arthere/global/config/JasyptConfig.java
  src/main/java/com/backend/arthere/member/application/.gitkeep
  src/main/java/com/backend/arthere/member/domain/.gitkeep
  src/main/java/com/backend/arthere/member/dto/.gitkeep
  src/main/java/com/backend/arthere/member/exception/.gitkeep
  src/main/java/com/backend/arthere/member/presentation/.gitkeep
  src/main/resources/application.properties
Labels: chore, feat

#5 [chore] Github action CI 백엔드 스크립트를 등록한다.
  .github/workflows/backend.yml
Labels: chore

#9 [chore] github actions CD 설정 추가한다.
  .github/workflows/backend-ci-cd.yml
  .github/workflows/backend.yml
Labels: chore

#11 [chore] codedeploy 배포 관련 파일 수정
  .github/workflows/backend-ci-cd.yml
  appspec.yml
Labels: chore

#17 [chore] 서버 배포 환경 구축한다.
  appspec.yml
  build.gradle
  execute-deploy.sh
  src/main/java/com/backend/arthere/ArtHereApplication.java
  src/main/java/com/backend/arthere/global/WebRestController.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: chore, feat

#14 [feat] jasypt 암호화 키 환경변수 설정
  .github/workflows/backend-ci-cd.yml
  src/main/java/com/backend/arthere/global/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: feat

#16 [feat] 멤버 조회 기능을 구현한다.
  src/main/java/com/backend/arthere/ArtHereApplication.java
  src/main/java/com/backend/arthere/member/application/.gitkeep
  src/main/java/com/backend/arthere/member/application/MemberService.java
  src/main/java/com/backend/arthere/member/domain/.gitkeep
  src/main/java/com/backend/arthere/member/domain/Member.java
  src/main/java/com/backend/arthere/member/domain/MemberRepository.java
  src/main/java/com/backend/arthere/member/domain/Role.java
  src/main/java/com/backend/arthere/member/domain/SocialType.java
  src/main/java/com/backend/arthere/member/dto/.gitkeep
  src/main/java/com/backend/arthere/member/dto/request/MemberRequest.java
  src/main/java/com/backend/arthere/member/dto/response/MemberResponse.java
  src/main/java/com/backend/arthere/member/exception/.gitkeep
  src/main/java/com/backend/arthere/member/exception/MemberNotFoundException.java
  src/main/java/com/backend/arthere/member/presentation/.gitkeep
  src/main/java/com/backend/arthere/member/presentation/MemberController.java
Labels: feat

#18 [feat] jwt를 구현한다.
  build.gradle
  src/main/java/com/backend/arthere/auth/application/CustomUserDetailsService.java
  src/main/java/com/backend/arthere/auth/domain/Token.java
  src/main/java/com/backend/arthere/auth/domain/TokenRepository.java
  src/main/java/com/backend/arthere/auth/domain/UserPrincipal.java
  src/main/java/com/backend/arthere/auth/exception/FailedTokenAuthenticationException.java
  src/main/java/com/backend/arthere/auth/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/backend/arthere/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/backend/arthere/auth/jwt/JwtTokenAuthenticationFilter.java
  src/main/java/com/backend/arthere/auth/jwt/JwtTokenProvider.java
  src/main/java/com/backend/arthere/global/config/JasyptConfig.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feat

#19 [feat] Oauth2 구글 로그인 기능 구현
  build.gradle
  src/main/java/com/backend/arthere/auth/application/AuthService.java
  src/main/java/com/backend/arthere/auth/application/CustomOAuth2UserService.java
  src/main/java/com/backend/arthere/auth/domain/CurrentUser.java
  src/main/java/com/backend/arthere/auth/domain/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/backend/arthere/auth/domain/UserPrincipal.java
  src/main/java/com/backend/arthere/auth/dto/GoogleOAuth2UserInfo.java
  src/main/java/com/backend/arthere/auth/dto/OAuth2Attributes.java
  src/main/java/com/backend/arthere/auth/dto/OAuth2UserInfo.java
  src/main/java/com/backend/arthere/auth/dto/request/TokenRequest.java
  src/main/java/com/backend/arthere/auth/dto/response/TokenResponse.java
  src/main/java/com/backend/arthere/auth/exception/InvalidRefreshTokenException.java
  src/main/java/com/backend/arthere/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/com/backend/arthere/auth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/backend/arthere/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/arthere/auth/presentation/AuthController.java
  src/main/java/com/backend/arthere/auth/util/CookieUtils.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/global/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: feat
