Repository art-here/art-here-backend, pull requests merged in 2023-05, with the labels that each got.

#91 만족도 api 일부 구현, refactoring
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/arts/dto/request/ArtImageByAddressRequest.java
  src/main/java/com/backend/arthere/arts/dto/request/ArtImageByArtNameRequest.java
  src/main/java/com/backend/arthere/arts/dto/request/ArtImageByRevisionDateRequest.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/satisfactions/application/SatisfactionsService.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionType.java
  src/main/java/com/backend/arthere/satisfactions/domain/Satisfactions.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepository.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsRepository.java
  src/main/java/com/backend/arthere/satisfactions/dto/request/SaveSatisfactionsRequest.java
  src/main/java/com/backend/arthere/satisfactions/dto/response/SatisfactionsListResponse.java
  src/main/java/com/backend/arthere/satisfactions/exception/InvalidSatisfactionException.java
  src/main/java/com/backend/arthere/satisfactions/presentation/SatisfactionsController.java
  src/test/java/com/backend/arthere/satisfactions/domain/SatisfactionsRepositoryTest.java
Labels: refactoring, fix, feat

#92 [feat] 댓글 작성, 수정 기능을 구현한다.
  src/docs/asciidoc/comment.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/backend/arthere/comment/application/CommentService.java
  src/main/java/com/backend/arthere/comment/domain/Comment.java
  src/main/java/com/backend/arthere/comment/domain/CommentRepository.java
  src/main/java/com/backend/arthere/comment/dto/request/CommentRequest.java
  src/main/java/com/backend/arthere/comment/exception/CommentNotFoundException.java
  src/main/java/com/backend/arthere/comment/presentation/CommentController.java
  src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
  src/main/java/com/backend/arthere/member/exception/NotWriterException.java
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/comment/application/CommentServiceTest.java
  src/test/java/com/backend/arthere/comment/domain/CommentRepositoryTest.java
  src/test/java/com/backend/arthere/comment/domain/CommentTest.java
  src/test/java/com/backend/arthere/comment/presentation/CommentControllerTest.java
  src/test/java/com/backend/arthere/fixture/CommentFixtures.java
  src/test/java/com/backend/arthere/global/ControllerTest.java
Labels: docs, test, feat

#94 [feat] 댓글 조회, 삭제 기능 구현
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/comment.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/com/backend/arthere/comment/application/CommentService.java
  src/main/java/com/backend/arthere/comment/domain/CommentRepository.java
  src/main/java/com/backend/arthere/comment/dto/response/CommentPageResponse.java
  src/main/java/com/backend/arthere/comment/dto/response/CommentResponse.java
  src/main/java/com/backend/arthere/comment/presentation/CommentController.java
  src/main/java/com/backend/arthere/global/config/SecurityConfig.java
  src/main/java/com/backend/arthere/member/domain/Member.java
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/comment/application/CommentServiceTest.java
  src/test/java/com/backend/arthere/comment/domain/CommentRepositoryTest.java
  src/test/java/com/backend/arthere/comment/presentation/CommentControllerTest.java
  src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
  src/test/java/com/backend/arthere/dislike/presentation/DislikeControllerTest.java
  src/test/java/com/backend/arthere/fixture/CommentFixtures.java
  src/test/java/com/backend/arthere/global/ControllerTest.java
  src/test/java/com/backend/arthere/like/presentation/LikeControllerTest.java
  src/test/java/com/backend/arthere/member/domain/MemberTest.java
Labels: docs, test, feat

#95 [feat] 만족도 api 구현
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/details/domain/Details.java
  src/main/java/com/backend/arthere/satisfactions/application/SatisfactionsService.java
  src/main/java/com/backend/arthere/satisfactions/domain/Satisfactions.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepository.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/satisfactions/dto/response/GetTotalToDetailsResponse.java
  src/main/java/com/backend/arthere/satisfactions/dto/response/SatisfactionsCountResponse.java
  src/main/java/com/backend/arthere/satisfactions/dto/response/SatisfactionsListResponse.java
  src/main/java/com/backend/arthere/satisfactions/presentation/SatisfactionsController.java
  src/test/java/com/backend/arthere/satisfactions/domain/SatisfactionsRepositoryTest.java
Labels: fix, feat

#98 [refactor] 작품 세부 조회에 위도, 경도 데이터 추가
  src/main/java/com/backend/arthere/details/application/DetailsService.java
  src/main/java/com/backend/arthere/details/domain/Details.java
  src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/backend/arthere/details/application/DetailsServiceTest.java
  src/test/java/com/backend/arthere/details/domain/DetailsRepositoryTest.java
  src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
Labels: docs, refactoring, test

#99 feat: 만족도 관련 api
  src/main/java/com/backend/arthere/arts/domain/Arts.java
  src/main/java/com/backend/arthere/arts/exception/ArtsNotFoundException.java
  src/main/java/com/backend/arthere/satisfactions/application/SatisfactionsService.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionType.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepository.java
  src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/satisfactions/dto/request/CreateSatisfactionsRequest.java
  src/main/java/com/backend/arthere/satisfactions/dto/response/GetTotalToDetailsResponse.java
  src/main/java/com/backend/arthere/satisfactions/dto/response/SatisfactionsListResponse.java
  src/main/java/com/backend/arthere/satisfactions/dto/response/SatisfactionsResponse.java
  src/main/java/com/backend/arthere/satisfactions/presentation/SatisfactionsController.java
  src/main/java/com/backend/arthere/starRatings/domain/StarRatings.java
  src/main/java/com/backend/arthere/starRatings/domain/StarRatingsCustomRepository.java
  src/main/java/com/backend/arthere/starRatings/domain/StarRatingsCustomRepositoryImpl.java
  src/main/java/com/backend/arthere/starRatings/domain/StarRatingsRepository.java
Labels: refactoring, feat

#100 [feat] 로그인 완료 후 사용자의 Role 반환
  src/main/java/com/backend/arthere/auth/domain/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/backend/arthere/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
  src/main/java/com/backend/arthere/member/domain/Role.java
  src/main/java/com/backend/arthere/member/exception/InvalidRoleException.java
  src/main/resources/application-local.yml
Labels: feat
